ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PRODUCT_DRAFT_CREATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PRODUCT_DRAFT_SUBMITTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PRODUCT_PUBLISHED';
